---
- name: "delete node from disk"
  vmware_guest:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.username }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    datacenter: "{{ openshift_vcenter.datacenter }}"
    folder: "{{ openshift_vcenter.folder }}"
    cluster: "{{ openshift_vcenter.cluster }}"
    template: "{{ openshift_rhcos_template_uuid }}"
    name: "{{ item }}"
    state: "absent"
  loop: "{{ bootstrap_nodes_list + master_nodes_list + worker_nodes_list}}"
