---
# defaults file for provision_vmware_node

openshift_rhcos_template_name: "rhcos"
openshift_rhcos_template_custom_attributes:
  - name: "disk.EnableUUID"
    value: "TRUE"
  - name: "guestinfo.ignition.config.data.encoding"
    value: "base64"
  - name: "guestinfo.ignition.config.data"
    value: "CHANGEME"
#    value: "{{ lookup('file', bootstrap_node.ignition_file_path) }}"

ignition_files_path: "{{ ansible_env.HOME }}/{{ openshift_working_directory_name }}"

bootstrap_nodes_list:
  - "ocp-bootstrap"

bootstrap_node:
  name: "ocp-bootstrap_node"
  ram: "16384"
  cpus: "4"
  disk:
    size: "120"
    type: "thin"
  ignition_file_path: "{{ ignition_files_path }}/append-bootstrap.ign"

master_nodes_list:
  - "ocp-master1"
  - "ocp-master2"
  - "ocp-master3"

master_node:
  ram: "16384"
  cpus: "4"
  disk:
    size: "120"
    type: "thin"
  ignition_file_path: "{{ ignition_files_path }}/master.ign"

worker_nodes_list:
  - "ocp-worker1"
  - "ocp-worker2"
  - "ocp-worker3"

worker_node:
  ram: "16384"
  cpus: "4"
  disk:
    size: "120"
    type: "thin"
  ignition_file_path: "{{ ignition_files_path }}/worker.ign"
