---
- name: "install http packages"
  package:
    name: "{{ http_server_package_name }}"
    state: "installed"

- name: "start http service"
  service:
    name: "{{ http_server_service_name }}"
    state: "started"

- name: "create ignition files http directory"
  file:
    path: "{{ http_server_data_dir }}/{{ http_server_ignition_files_dir_name }}"
    state: "directory"
    owner: "{{ http_server_user }}"
    group: "{{ http_server_group }}"
    recurse: true

- name: "allow http on firewalld"
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: "true"
  loop: "{{ firewall_service_rules }}"

- name: "allow port on firewalld"
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: "true"
  loop: "{{ firewall_port_rules }}"
