---
- name: "set ssh_key_path"
  set_fact:
    ssh_key_path: "{{ ansible_env.HOME }}/.ssh/{{ ssh_key_name }}"
  tags:
    - install_config

- stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key_exists
  tags:
    - install_config

- name: "generate ssh key"
  shell: "ssh-keygen -f {{ ssh_key_path }} -N ''"
  when: not ssh_key_exists.stat.exists
  tags:
    - install_config

- name: "set ssh_key_pub_path"
  set_fact:
    ssh_key_pub_path: "{{ ssh_key_path }}.pub"
  tags:
    - install_config

- name: "set ssh_key var"
  set_fact:
    ssh_key: "{{ lookup('file', ssh_key_pub_path) }}"
  tags:
    - install_config
