---
- name: "install tools on bastion"
  package:
    name: "{{ item }}"
    state: "installed"
  loop: "{{ tools_packages }}"

- stat:
    path: "{{ ansible_env.HOME }}/.ssh/{{ ssh_key_name }}"
  register: ssh_key_exists

- name: "generate ssh key"
  shell: "ssh-keygen -f {{ ansible_env.HOME }}/.ssh/{{ ssh_key_name }} -N ''"
  when: not ssh_key_exists.stat.exists
