---
# tasks file for configure_bastion

- include_tasks: "generate_ssh_key.yaml"
  tags:
    - install_config
- include_tasks: "get_openshift_binary.yaml"
  tags:
    - install_config
- include_tasks: "install_oc_client.yaml"
  tags:
    - install_config
- include_tasks: "configure_http_server.yaml"
- include_tasks: "create_openshift_install_config_files.yaml"
  tags:
    - install_config
