---
- name: "add custom attributes to rhcos ova"
  vmware_guest_custom_attributes:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.username }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    uuid: "{{ openshift_rhcos_template_uuid }}"
    state: present
    attributes: "{{ openshift_rhcos_template_custom_attributes }}"
