---
- name: "set VM config param for ignition file"
  set_fact:
    openshift_ignition_config_param:
      - key: guestinfo.ignition.config.data
        value: "{{ lookup('file', worker_node.ignition_file_path) }}"

- name: "set VM config parameters"
  set_fact:
    openshift_config_params: "{{ openshift_common_config_params + openshift_ignition_config_param }}"

- name: "clone from rhcos ova for worker"
  vmware_guest:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.username }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    datacenter: "{{ openshift_vcenter.datacenter }}"
    folder: "{{ openshift_vcenter.folder }}"
    cluster: "{{ openshift_vcenter.cluster }}"
    template: "{{ openshift_rhcos_template_uuid }}"
    name: "{{ item }}"
    state: "poweredoff"
    disk:
    - datastore: "{{ openshift_vcenter.default_datastore }}"
      type: "{{ worker_node.disk.type }}"
      size_gb: "{{ worker_node.disk.size }}"
    hardware:
      memory_mb: "{{ worker_node.ram }}"
      memory_reservation_lock: true
      memory_reservation: "{{ worker_node.ram }}"
      num_cpus: "{{ worker_node.cpus }}"
    customvalues: "{{ openshift_config_params }}"
  loop: "{{ worker_nodes_list }}"

#TODO: not used in bootstrap?
- name: "add custom attributes to rhcos ova"
  vmware_guest_custom_attributes:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.username }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    datacenter: "{{ openshift_vcenter.datacenter }}"
    folder: "{{ openshift_vcenter.folder }}"
    name: "{{ item }}"
    state: present
    attributes:
      - name: "disk.EnableUUID"
        value: "TRUE"
      - name: "guestinfo.ignition.config.data.encoding"
        value: "base64"
      - name: "guestinfo.ignition.config.data"
        value: "{{ lookup('file', worker_node.ignition_file_path) }}"
  loop: "{{ worker_nodes_list }}"
