---
- name: "clone from rhcos ova for masters"
  vmware_guest:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.user }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    datacenter: "{{ openshift_vcenter.datacenter }}"
    folder: "{{ openshift_vcenter.folder }}"
    cluster: "{{ openshift_vcenter.cluster }}"
    template: "{{ openshift_vcenter.rhcos_template }}"
    name: "{{ item }}"
    state: "poweredoff"
    disk:
    - datastore: "{{ openshift_vcenter.default_datastore }}"
      type: "{{ worker_node.disk.type }}"
      size_gb: "{{ worker_node.disk.size }}"
    hardware:
      memory: "{{ worker_node.ram }}"
      num_cpus: "{{ worker_node.cpus }}"
    customvalues:
      - key: disk.EnableUUID
        value: 'TRUE'
      - key: sched.cpu.latencySensitivity
        value: 'high'
      - key: guestinfo.ignition.config.data.encoding
        value: 'base64'
      - key: guestinfo.ignition.config.data
        value: "{{ lookup('file', worker_node.ignition_file_path) }}"
  loop: "{{ worker_nodes_list }}"
