---
- name: get vm node facts
  vmware_guest_facts:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.username }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    datacenter: "{{ openshift_vcenter.datacenter }}"
    folder: "{{ openshift_vcenter.folder }}"
    name: "{{ item }}"
  loop: "{{ bootstrap_nodes_list + master_nodes_list + worker_nodes_list}}"
  register: r_node_facts

- debug:
    msg: "{{ item.instance.hw_name }} -> {{ item.instance.hw_eth0.macaddress }}"
  loop: "{{ r_node_facts.results }}"
