---
- name: "set the state of node to poweron"
  vmware_guest_powerstate:
    hostname: "{{ openshift_vcenter.host }}"
    username: "{{ openshift_vcenter.username }}"
    password: "{{ openshift_vcenter.password }}"
    validate_certs: no
    folder: "{{ openshift_vcenter.folder }}"
    name: "{{ item }}"
    state: "powered-on"
  loop: "{{ bootstrap_nodes_list + master_nodes_list + worker_nodes_list }}"
