---
- name: "Poweron openshift nodes on VMware"
  hosts: localhost
  tasks:
    - include_role:
        name: "provision_vmware_node"
        tasks_from: "poweron_node.yaml"
      loop: "{{ bootstrap_nodes_list }}"

    - include_role:
        name: "provision_vmware_node"
        tasks_from: "poweron_node.yaml"
      loop: "{{ master_nodes_list }}"

    - include_role:
        name: "provision_vmware_node"
        tasks_from: "poweron_node.yaml"
      loop: "{{ worker_nodes_list }}"
