---
- name: get server profiles
  oneview_server_profile_facts:
  register: sp
  delegate_to: localhost
  run_once: True

#- fail:

- name: get server hardwares
  oneview_server_hardware_facts:
  register: hw
  delegate_to: localhost
  run_once: True

- debug:
    var: sp
    verbosity: 2
  run_once: True

- debug:
    var: hw
    verbosity: 2
  run_once: True

- debug:
    msg: "server {{ item.name }} in bay {{ item.position }} has state {{ item.state }} with {{ item.memoryMb }} memory. it is a {{ item.shortModel }}. {{ item.processorCoreCount }} cores are spread across {{ item.processorCount }} at {{ item.processorSpeedMhz }} ({{ item.processorType }})."
    verbosity: 2
  with_items:
  - "{{ hw.ansible_facts.server_hardwares }}"
  run_once: True

- name: set CNS node facts
  set_fact:
    server_profile_template: "{{ cns_server_profile_template }}"
    deployment_plan: "{{ cns_deployment_plan }}"
  when:
  - "'glusterfs' in group_names"

- name: set master node facts
  set_fact:
    server_profile_template: "{{ master_server_profile_template }}"
    deployment_plan: "{{ master_deployment_plan }}"
  when:
  - "'masters' in group_names"

- name: set lbnfs node facts
  set_fact:
    server_profile_template: "{{ lbnfs_server_profile_template }}"
    deployment_plan: "{{ lbnfs_deployment_plan }}"
  when:
  - "'lb' in group_names"
  - "'nfs' in group_names"

- name: set infra node facts
  set_fact:
    server_profile_template: "{{ infra_server_profile_template }}"
    deployment_plan: "{{ infra_deployment_plan }}"
  when:
  - "'infra' in group_names"

- debug:
    var: deployment_plan
- debug:
    var: server_profile_template

#- fail:


- name: get network facts
  oneview_ethernet_network_facts:
  delegate_to: localhost
  run_once: True
  register: nw

- debug:
    var: nw
    verbosity: 2
  run_once: True

- name: set network uri
  set_fact:
    network: "{{ network|combine({'uri': item }) }}"
  with_items:  "{{ nw|json_query(network_name_query) }}"
  vars:
    network_name_query:  "ansible_facts.ethernet_networks[?name=='{{ network.name }}'].uri"
  run_once: True

- debug:
    var: network
    verbosity: 2
  run_once: True

- name: set hardware facts
  set_fact:
    preassigned: True
    hardware_name: "{{ enclosure_name }}, bay {{ enclosure_bay }}"
  when:
  - enclosure_name is defined
  - enclosure_bay is defined

- debug:
    var: preassigned
    verbosity: 2

- debug:
    var: hardware_name
    verbosity: 2
  when: preassigned

- name: set hardware uri
  set_fact:
    hardware_uri: "{{ item }}"
  with_items:  "{{ hw|json_query(hardware_name_query) }}"
  vars:
    hardware_name_query:  "ansible_facts.server_hardwares[?name=='{{  hardware_name }}'].uri"
  when: preassigned

- debug:
    var: hardware_uri
    verbosity: 2
  when: preassigned

- debug:
    var: server_profile_template
    verbosity: 2

#- fail:
#  run_once: True
