---
# OpenShift variables
openshift_version: "4.2.7"
openshift_cluster_name: "ocp-cluster"

openshift_base_domain: "example.com"
openshift_worker_replicas_number: "0"
openshift_master_replicas_number: "3"

openshift_pull_secret: 'your_pull_secret'

# OpenShift nodes list
bootstrap_nodes_list:
  - "ocp-bootstrap"

master_nodes_list:
  - "ocp-master1"
  - "ocp-master2"
  - "ocp-master3"

worker_nodes_list:
  - "ocp-worker1"
  - "ocp-worker2"
  - "ocp-worker3"

# vCenter variables
openshift_vcenter:
  host: "your_vcenter_server"
  username: "your_vsphere_username"
  password: "your_vsphere_password"
  datacenter: "your_datacenter"
  cluster: "your_cluster"
  default_datastore: "your_datastore"

openshift_rhcos_template_name: "rhcos_template_name"

# Proxy variables (if it is used)
openshift_proxy:
  http: "http://proxy_server:9000"
  https: "http://proxy_server:9000"
  no_proxy: "localhost"
