---
- name: unassign server profile
  oneview_server_profile:
    state: absent
    data:
      name: "{{ inventory_hostname.split('.').0 }}"
  register: output
  delegate_to: localhost
  when:
  - profile_facts.ansible_facts.server_profiles|length == 1
- debug:
    var: output
    verbosity: 2
